<?php
/** @var $hotel \Infotrip\Domain\Entity\Hotel */
/** @var $hotelInfo \Infotrip\HotelParser\Entity\HotelInfo */
$hotelInfo = $hotel->getExternalHotelInfo();
/** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
    $routeHelper = $viewHelpers['routeHelper'];

    //throw new Exception('test');
    require_once $this->getTemplatePath() . 'includes/header.phtml';
?>


    <div class="container">
        <ul class="breadcrumb">
            <li><a href="<?= $routeHelper->getHomepageUrl(); ?>">Home</a>
            </li>
            <li><a href="<?= $routeHelper->getContinentUrl($hotel->getContinentName()); ?>"><?= $hotel->getContinentName(); ?></a>
            </li>
            <li><a href="<?= $routeHelper->getCountryUrl($hotel->getCountryCode()); ?>">
                    <?= $hotel->getCountryName(); ?>
                </a>
            </li>
            <li><a href="<?= $routeHelper->getCityUrl($hotel->getCityUnique()); ?>"><?= $hotel->getCityHotel(); ?></a></li>
            <li class="active"><?php echo $hotel->getName(); ?></li>
        </ul>
        <div class="booking-item-details">
            <header class="booking-item-header">
                <div class="row">
                    <div class="col-md-9">
                        <h2 class="lh1em"><?php echo $hotel->getName(); ?></h2>
                        <p class="lh1em text-small"><i class="fa fa-map-marker"></i>
                            <?= $hotel->getAddress(); ?>, <?= $hotel->getZip(); ?>, <?= $hotel->getCityHotel(); ?>
                        </p>
                    </div>
                    <div class="col-md-3">
                        <p class="booking-item-header-price"><small>price from</small>  <span class="text-lg"><?= $hotel->getCurrencucodeShort(); ?><?= $hotel->getMinrate(); ?></span>/night</p>
                    </div>
                </div>
            </header>
            <div class="row">
                <div class="col-md-6">
                    <div class="tabbable booking-details-tabbable">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class="active"><a href="/#tab-1" data-toggle="tab"><i class="fa fa-camera"></i>Photos</a>
                            </li>
                            <li><a href="#google-map-tab" data-toggle="tab"><i class="fa fa-map-marker"></i>On the Map</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="tab-1">
                                <div class="fotorama" id="hotelImageGallery" data-allowfullscreen="true" data-nav="thumbs" data-width="100%">
                                    <?php foreach ($hotel->getImages() as $image): ?>
                                        <img src="<?= $image->getSrc(); ?>"
                                             <?php if (! $image->isCached()): ?>
                                             data-no-cache-image="1"
                                             <?php endif; ?>
                                             data-hotel-id="<?= $hotel->getId(); ?>" data-city-unique="<?= $hotel->getCityUnique(); ?>"
                                             alt="Gallery image of this property"
                                             title="Gallery image of this property">
                                    <?php endforeach; ?>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="google-map-tab">
                                <div id="map-canvas" style="width:100%; height:500px;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 mt40 to-load <?php if($hotelInfo instanceof \Infotrip\HotelParser\Entity\NullHotelInfo): ?> bg-holder <?php endif; ?>">
                    <?php if($hotelInfo instanceof \Infotrip\HotelParser\Entity\NullHotelInfo): ?><div class="bg-mask"></div><?php endif; ?>
                    <div class="booking-item-meta">
                        <h2 class="lh1em">
                            <span id="hotelInfo_ratingText"><?= $hotelInfo->getRatingText(); ?>!</span>
                        </h2>
                        <h3><span id="hotelInfo_guestRecommendPercent"><?= $hotelInfo->getGuestRecommendPercent(); ?></span>% <small >of guests recommend</small></h3>
                        <div class="booking-item-rating">
                            <ul class="icon-list icon-group booking-item-rating-stars" id="hotelInfostarsScore">
                                <?php for ($i= 1; $i<=$hotelInfo->getStarsScore(); $i++): ?>
                                    <li><i class="fa fa-star"></i></li>
                                <?php endfor; ?>
                            </ul><span class="booking-item-rating-number"><b><span id="hotelInfo_reviewScoreTotal"><?= $hotelInfo->getReviewScoreTotal(); ?></span></b> of 5 <small class="text-smaller">guest rating</small></span>
                            <p class="text-default">based on <span id="hotelInfo_totalReviewsNo"><?= $hotelInfo->getTotalReviewsNo(); ?></span> reviews</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-7">
                            <div class="bg-holder"><div class="bg-mask"></div></div>
                            <h4 class="lh1em">Traveler rating</h4>
                            <ul class="list booking-item-raiting-list" id="hotelInforeviewScores">
                                <?php foreach ($hotelInfo->getReviewScores() as $reviewScore): ?>
                                <li>
                                    <div class="booking-item-raiting-list-title">
                                        <?= $reviewScore->getLabel(); ?>
                                    </div>
                                    <div class="booking-item-raiting-list-bar">
                                        <div style="width:<?= $reviewScore->getPercent(); ?>%;"></div>
                                    </div>
                                    <div class="booking-item-raiting-list-number">
                                        <?= $reviewScore->getScore(); ?>
                                    </div>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <div class="col-md-5">
                            <h4 class="lh1em">Summary</h4>
                            <ul class="list booking-item-raiting-summary-list" id="hotelInforeviewFunctionsScores">
                                <?php foreach ($hotelInfo->getReviewFunctionsScores() as $reviewScore): ?>
                                <li>
                                    <div class="booking-item-raiting-list-title"><?= $reviewScore->getLabel(); ?></div>
                                    <ul class="icon-group booking-item-rating-stars">
                                        <?php for($i=1; $i<=$reviewScore->getStarBase5(); $i++): ?>
                                        <li><i class="fa fa-smile-o"></i></li>
                                        <?php endfor; ?>
                                    </ul>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gap"></div>
            <h3>Available Rooms</h3>
            <div class="row">
                <div class="col-md-9">
                    <div class="booking-item-dates-change">
                        <form method="get"
                              id="checkAvailabilityForm"
                              action="<?= $routeHelper->getHotelCheckAvailabilityUrl($hotel->getName(), $hotel->getId()); ?>"
                              target="_blank">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-daterange" data-date-format="MM d, D">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group form-group-icon-left"><i class="fa fa-calendar input-icon input-icon-hightlight"></i>
                                                    <label>Check in</label>
                                                    <input class="form-control" name="start" type="text" />
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group form-group-icon-left"><i class="fa fa-calendar input-icon input-icon-hightlight"></i>
                                                    <label>Check out</label>
                                                    <input class="form-control" name="end" type="text" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group form-group-select-plus">
                                        <label>Adults</label>
                                        <div class="btn-group btn-group-select-num" data-toggle="buttons">
                                            <label class="btn btn-primary active">
                                                <input type="radio" name="adults" value="1" />1</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="adults" value="2" />2</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="adults" value="3" />3</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="adults" value="noRadio" />4+</label>
                                        </div>
                                        <select name="adultsSelect" class="form-control hidden">
                                            <?php for($i=1; $i<=6; $i++): ?>
                                            <option value="<?= $i; ?>"><?= $i; ?></option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group form-group-select-plus">
                                        <label>Children</label>
                                        <div class="btn-group btn-group-select-num" data-toggle="buttons">
                                            <label class="btn btn-primary active">
                                                <input type="radio" name="childrens" value="0" />0</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="childrens" value="1" />1</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="childrens" value="2" />2</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="childrens" value="noRadio"/>2+</label>
                                        </div>
                                        <select name="childrensSelect" class="form-control hidden">
                                            <?php for($i=1; $i<=6; $i++): ?>
                                                <option value="<?= $i; ?>"><?= $i; ?></option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group form-group-select-plus">
                                        <label>Rooms</label>
                                        <div class="btn-group btn-group-select-num" data-toggle="buttons">
                                            <label class="btn btn-primary active">
                                                <input type="radio" name="rooms" value="1" />1</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="rooms" value="2" />2</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="rooms" value="3" />3</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="rooms" value="noRadio"/>3+</label>
                                        </div>
                                        <select name="roomsSelect" class="form-control hidden">
                                            <?php for($i=1; $i<=6; $i++): ?>
                                                <option value="<?= $i; ?>"><?= $i; ?></option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <input type="hidden" name="hid" value="<?= $hotel->getId(); ?>">
                                    <input type="submit" name="checkAvailability" value="Check availability"
                                           id="checkAvailabilitySubmit"
                                           class="btn btn-primary">
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="gap gap-small"></div>

                </div>
                <div class="col-md-3">
                    <h4>About the Hotel</h4>
                    <p class="mb30">
                        <?= $hotel->getDescEn(); ?>
                    </p>
                </div>
            </div>


            <div class="row">
                <div class="col-md-12">

                    <h4>Hotels Near <?php echo $hotel->getName(); ?></h4>

                    <ul class="booking-list">
                        <?php for ($i=0; $i < 9; $i++): ?>
                            <?php if (isset($hotel->getRelatedHotels()[$i]) && ($relatedHotel = $hotel->getRelatedHotels()[$i])): ?>
                                <li>
                                    <a class="booking-item"
                                       href="<?= $routeHelper->getHotelUrl($relatedHotel->getName(), $relatedHotel->getId()); ?>"
                                       target="_blank">
                                        <div class="row">
                                            <div class="col-md-3" style="height: 130px; overflow: hidden;">
                                                <img src="<?= $relatedHotel->getImages()[0]->getSrc(); ?>"
                                                    <?php if (! $relatedHotel->getImages()[0]->isCached()): ?>
                                                        data-no-cache-image="1"
                                                    <?php endif; ?>
                                                     data-hotel-id="<?= $relatedHotel->getId(); ?>" data-city-unique="<?= $hotel->getCityUnique(); ?>"
                                                     alt="<?= $relatedHotel->getName(); ?> photo" title="hotel PORTO BAY RIO INTERNACIONAL rooftop pool" />
                                            </div>
                                            <div class="col-md-5">
                                                <h5 class="booking-item-title"><?= $relatedHotel->getName(); ?></h5>
                                                <p class="text-small"><?= $relatedHotel->getDescEn(); ?></p>
                                            </div>
                                            <div class="col-md-4"><span class="booking-item-price"><?= $relatedHotel->getCurrencucodeShort(); ?><?= $relatedHotel->getMinrate(); ?></span><span>/night</span>

                                            </div>
                                        </div>
                                    </a>
                                </li>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </ul>
                </div>
            </div>

        </div>
        <div class="gap gap-small"></div>
    </div>



    <footer id="main-footer">
        <div class="container">
            <div class="row row-wrap">
                <div class="col-md-3">
                    <a class="logo" href="/index.html">
                        <img src="/img/logo-invert.png" alt="Image Alternative text" title="Image Title" />
                    </a>
                    <p class="mb20">Booking, reviews and advices on hotels, resorts, flights, vacation rentals, travel packages, and lots more!</p>
                    <ul class="list list-horizontal list-space">
                        <li>
                            <a class="fa fa-facebook box-icon-normal round animate-icon-bottom-to-top" href="/#"></a>
                        </li>
                        <li>
                            <a class="fa fa-twitter box-icon-normal round animate-icon-bottom-to-top" href="/#"></a>
                        </li>
                        <li>
                            <a class="fa fa-google-plus box-icon-normal round animate-icon-bottom-to-top" href="/#"></a>
                        </li>
                        <li>
                            <a class="fa fa-linkedin box-icon-normal round animate-icon-bottom-to-top" href="/#"></a>
                        </li>
                        <li>
                            <a class="fa fa-pinterest box-icon-normal round animate-icon-bottom-to-top" href="/#"></a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-3">
                    <h4>Newsletter</h4>
                    <form>
                        <label>Enter your E-mail Address</label>
                        <input type="text" class="form-control">
                        <p class="mt5"><small>*We Never Send Spam</small>
                        </p>
                        <input type="submit" class="btn btn-primary" value="Subscribe">
                    </form>
                </div>
                <div class="col-md-2">
                    <ul class="list list-footer">
                        <li><a href="/#">About US</a>
                        </li>
                        <li><a href="/#">Press Centre</a>
                        </li>
                        <li><a href="/#">Best Price Guarantee</a>
                        </li>
                        <li><a href="/#">Travel News</a>
                        </li>
                        <li><a href="/#">Jobs</a>
                        </li>
                        <li><a href="/#">Privacy Policy</a>
                        </li>
                        <li><a href="/#">Terms of Use</a>
                        </li>
                        <li><a href="/#">Feedback</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h4>Have Questions?</h4>
                    <h4 class="text-color">+1-202-555-0173</h4>
                    <h4><a href="/#" class="text-color">support@traveler.com</a></h4>
                    <p>24/7 Dedicated Customer Support</p>
                </div>

            </div>
        </div>
    </footer>

    <script src="/js/jquery.js"></script>
    <script src="/js/bootstrap.js"></script>
    <script src="/js/slimmenu.js"></script>
    <script src="/js/bootstrap-datepicker.js"></script>
    <script src="/js/bootstrap-timepicker.js"></script>
    <script src="/js/nicescroll.js"></script>
    <script src="/js/dropit.js"></script>
    <script src="/js/ionrangeslider.js"></script>
    <script src="/js/icheck.js"></script>
    <script src="/js/fotorama.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script src="/js/typeahead.js"></script>
    <script src="/js/card-payment.js"></script>
    <script src="/js/magnific.js"></script>
    <script src="/js/owl-carousel.js"></script>
    <script src="/js/fitvids.js"></script>
    <script src="/js/tweet.js"></script>
    <script src="/js/countdown.js"></script>
    <script src="/js/gridrotator.js"></script>
    <script src="/js/custom.js"></script>

    <script>
        var nonCachedImages = new Array();
        $('[data-no-cache-image]').each(function (index) {
            var $this = $(this);
            nonCachedImages.push({
                src: $this.attr('src'),
                hotelId: $this.data('hotel-id'),
                cityUnique: $this.data('city-unique')
            });
        });

        if (nonCachedImages.length >= 1) {
            $.post(
                "<?= $routeHelper->getCacheImagesUrl(); ?>",
                {
                    nonCachedImages: nonCachedImages
                }
            ).done(function (data) {
            });
        }
    </script>

    <?php if ($hotelInfo instanceof \Infotrip\HotelParser\Entity\NullHotelInfo): ?>
    <script>

        $.ajax({
            type: 'POST',
            url: '<?= $routeHelper->getCacheHotelUrl(); ?>',
            data: {
                hid: <?= $hotel->getId(); ?>
            },
            success: function (data) {

                $('.bg-mask').remove();

                if (data["externalHotelInfo"]) {
                    for (var key in data["externalHotelInfo"]) {
                        var $placeholderElm = $('#hotelInfo_' + key);
                        var $placeholderIterator = $('#hotelInfo' + key);

                        if ($placeholderElm.length) {
                            $placeholderElm.html(
                                data["externalHotelInfo"][key]
                            );
                        }

                        if(key === 'starsScore') {
                            for (var i=1; i<=data["externalHotelInfo"][key]; i++ ) {
                                $placeholderIterator.append('<i class="fa fa-star"></i>')
                            }
                        } else if(key === 'reviewScores') {
                            if (data["externalHotelInfo"][key].length) {
                                for (var i=0; i<data["externalHotelInfo"][key].length; i++) {
                                    var label = data["externalHotelInfo"][key][i]["label"];
                                    var score = data["externalHotelInfo"][key][i]["score"];
                                    var percent = data["externalHotelInfo"][key][i]["percent"];

                                    $placeholderIterator.append(
                                        '<li><div class="booking-item-raiting-list-title">'+label+'</div><div class="booking-item-raiting-list-bar"><div style="width:'+percent+'%;"></div></div><div class="booking-item-raiting-list-number">'+score+'</div></li>'
                                    )
                                }
                            }
                        } else if(key === 'reviewFunctionsScores') {
                            if (data["externalHotelInfo"][key].length) {
                                for (var i=0; i<data["externalHotelInfo"][key].length; i++) {
                                    var label = data["externalHotelInfo"][key][i]["label"];
                                    var starBase5 = data["externalHotelInfo"][key][i]["starBase5"];

                                    var html = '<li><div class="booking-item-raiting-list-title">'+label+'</div><ul class="icon-group booking-item-rating-stars">'
                                    for (var j=1; j<=starBase5; j++) {
                                        html += '<li><i class="fa fa-smile-o"></i></li>';
                                    }
                                    html += '</ul></li>';
                                    $placeholderIterator.append(html)
                                }
                            }
                        } else if(key === 'hotelComments') {
                            if (data["externalHotelInfo"][key].length) {
                                for (var i=0; i<data["externalHotelInfo"][key].length; i++) {
                                    var reviewComment = data["externalHotelInfo"][key][i]["reviewComment"];
                                    var reviewUser = data["externalHotelInfo"][key][i]["reviewUser"];
                                    var reviewUserLocation = data["externalHotelInfo"][key][i]["reviewUserLocation"];

                                    $placeholderIterator.append(
                                        '<li><div class="row"><div class="col-md-2"><div class="booking-item-review-person"><p class="booking-item-review-person-name">'+reviewUser+'</p><p class="booking-item-review-person-loc">'+reviewUserLocation+'</p></div></div><div class="col-md-10"><div class="booking-item-review-content"><p>'+reviewComment+'</p></div></div></div></li>'
                                    )
                                }
                            }
                        }
                    }

                    <?php if (
                        (count($hotel->getImages()) <= 1)
                    ): ?>
                    if(key === 'images') {
                        if (data["externalHotelInfo"][key].length) {
                            // get the API fotorama object.
                            var fotorama = $('#hotelImageGallery').data('fotorama');
                            for (var i=0; i<data["externalHotelInfo"][key].length; i++) {
                                var src = data["externalHotelInfo"][key][i]["src"];
                                fotorama.push({img: src, thumb: src});
                            }
                        }
                    }
                    <?php endif; ?>

                }
            },
            dataType: 'json',
            beforeSend: function (jqXHT, settings) {
            }
        });


    </script>
    <?php endif; ?>
</div>
</body>

</html>


