<?php

/** @var \Infotrip\Domain\Entity\Hotel $hotel */

/** @var \Infotrip\HotelParser\Entity\HotelInfo $hotelInfo */
$hotelInfo = $hotel->getExternalHotelInfo();

/** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
    $routeHelper = $viewHelpers['routeHelper'];

    //throw new Exception('test');
    require_once $this->getTemplatePath() . 'includes/header.phtml';
?>


    <div class="container">
        <ul class="breadcrumb">
            <li><a href="<?= $routeHelper->getHomepageUrl(); ?>">Home</a>
            </li>
            <li><a href="<?= $routeHelper->getHotelsInUrl('', '', $hotel->getContinentName()); ?>"><?= $hotel->getContinentName(); ?></a>
            </li>
            <li><a href="<?= $routeHelper->getHotelsInUrl('', $hotel->getCountryCode()); ?>">
                    <?= $hotel->getCountryName(); ?>
                </a>
            </li>
            <li><a href="<?= $routeHelper->getHotelsInUrl($hotel->getCityUnique()); ?>"><?= $hotel->getCityHotel(); ?></a></li>
            <li class="active"><?php echo $hotel->getName(); ?></li>
        </ul>
        <div class="booking-item-details">
            <header class="booking-item-header">
                <div class="row">
                    <div class="col-md-9">
                        <h2 class="lh1em"><?php echo $hotel->getName(); ?></h2>
                        <p class="lh1em text-small"><i class="fa fa-map-marker"></i>
                            <?= $hotel->getAddress(); ?>, <?= $hotel->getZip(); ?>, <?= $hotel->getCityHotel(); ?>
                        </p>
                    </div>
                    <div class="col-md-3">
                        <p class="booking-item-header-price"><small>price from</small>  <span class="text-lg"><?= $hotel->getCurrencucodeShort(); ?><?= $hotel->getMinrate(); ?></span>/night</p>
                    </div>
                </div>
            </header>
            <div class="row">
                <div class="col-md-6">
                    <div class="tabbable booking-details-tabbable">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class="active"><a href="/#tab-1" data-toggle="tab"><i class="fa fa-camera"></i>Photos</a>
                            </li>
                            <li><a href="#google-map-tab" data-toggle="tab"><i class="fa fa-map-marker"></i>On the Map</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="tab-1">
                                <div class="fotorama" id="hotelImageGallery" data-allowfullscreen="true" data-nav="thumbs" data-width="100%">
                                    <?php foreach ($hotel->getImages() as $image): ?>
                                        <img src="<?= $image->getSrc(); ?>"
                                             <?php if (! $image->isCached()): ?>
                                             data-no-cache-image="1"
                                             <?php endif; ?>
                                             data-hotel-id="<?= $hotel->getId(); ?>" data-city-unique="<?= $hotel->getCityUnique(); ?>"
                                             alt="Gallery image of this property"
                                             title="Gallery image of this property">
                                    <?php endforeach; ?>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="google-map-tab">
                                <div id="map-canvas" style="width:100%; height:500px;"></div>
                                <div id="directionsPanel"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 mt40 to-load <?php if($hotelInfo instanceof \Infotrip\HotelParser\Entity\NullHotelInfo): ?> bg-holder <?php endif; ?>">
                    <?php if($hotelInfo instanceof \Infotrip\HotelParser\Entity\NullHotelInfo): ?><div class="bg-mask"></div><?php endif; ?>
                    <div class="booking-item-meta">
                        <h2 class="lh1em">
                            <span id="hotelInfo_ratingText"><?= $hotelInfo->getRatingText(); ?>!</span>
                        </h2>
                        <h3><span id="hotelInfo_guestRecommendPercent"><?= $hotelInfo->getGuestRecommendPercent(); ?></span>% <small >of guests recommend</small></h3>
                        <div class="booking-item-rating">
                            <ul class="icon-list icon-group booking-item-rating-stars" id="hotelInfostarsScore">
                                <?php for ($i= 1; $i<=$hotelInfo->getStarsScore(); $i++): ?>
                                    <li><i class="fa fa-star"></i></li>
                                <?php endfor; ?>
                            </ul><span class="booking-item-rating-number"><b><span id="hotelInfo_reviewScoreTotal"><?= $hotelInfo->getReviewScoreTotal(); ?></span></b> of 5 <small class="text-smaller">guest rating</small></span>
                            <p class="text-default">based on <span id="hotelInfo_totalReviewsNo"><?= $hotelInfo->getTotalReviewsNo(); ?></span> reviews</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-7">
                            <div class="bg-holder"><div class="bg-mask"></div></div>
                            <h4 class="lh1em">Traveler rating</h4>
                            <ul class="list booking-item-raiting-list" id="hotelInforeviewScores">
                                <?php foreach ($hotelInfo->getReviewScores() as $reviewScore): ?>
                                <li>
                                    <div class="booking-item-raiting-list-title">
                                        <?= $reviewScore->getLabel(); ?>
                                    </div>
                                    <div class="booking-item-raiting-list-bar">
                                        <div style="width:<?= $reviewScore->getPercent(); ?>%;"></div>
                                    </div>
                                    <div class="booking-item-raiting-list-number">
                                        <?= $reviewScore->getScore(); ?>
                                    </div>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <div class="col-md-5">
                            <h4 class="lh1em">Summary</h4>
                            <ul class="list booking-item-raiting-summary-list" id="hotelInforeviewFunctionsScores">
                                <?php foreach ($hotelInfo->getReviewFunctionsScores() as $reviewScore): ?>
                                <li>
                                    <div class="booking-item-raiting-list-title"><?= $reviewScore->getLabel(); ?></div>
                                    <ul class="icon-group booking-item-rating-stars">
                                        <?php for($i=1; $i<=$reviewScore->getStarBase5(); $i++): ?>
                                        <li><i class="fa fa-smile-o"></i></li>
                                        <?php endfor; ?>
                                    </ul>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gap"></div>
            <h3>Available Rooms</h3>
            <div class="row">
                <div class="col-md-9">
                    <div class="booking-item-dates-change">
                        <form method="get"
                              id="checkAvailabilityForm"
                              action="<?= $routeHelper->getHotelCheckAvailabilityUrl($hotel->getName(), $hotel->getId()); ?>"
                              target="_blank">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-daterange" data-date-format="MM d, D">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group form-group-icon-left"><i class="fa fa-calendar input-icon input-icon-hightlight"></i>
                                                    <label>Check in</label>
                                                    <input class="form-control" name="start" type="text" id="checkInDateInput" />
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group form-group-icon-left"><i class="fa fa-calendar input-icon input-icon-hightlight"></i>
                                                    <label>Check out</label>
                                                    <input class="form-control" name="end" type="text" id="checkOutDateInput" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group form-group-select-plus">
                                        <label>Adults</label>
                                        <div class="btn-group btn-group-select-num" data-toggle="buttons">
                                            <label class="btn btn-primary active">
                                                <input type="radio" name="adults" value="1" />1</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="adults" value="2" />2</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="adults" value="3" />3</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="adults" value="noRadio" />4+</label>
                                        </div>
                                        <select name="adultsSelect" class="form-control hidden">
                                            <?php for($i=1; $i<=6; $i++): ?>
                                            <option value="<?= $i; ?>"><?= $i; ?></option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group form-group-select-plus">
                                        <label>Children</label>
                                        <div class="btn-group btn-group-select-num" data-toggle="buttons">
                                            <label class="btn btn-primary active">
                                                <input type="radio" name="childrens" value="0" />0</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="childrens" value="1" />1</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="childrens" value="2" />2</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="childrens" value="noRadio"/>2+</label>
                                        </div>
                                        <select name="childrensSelect" class="form-control hidden">
                                            <?php for($i=1; $i<=6; $i++): ?>
                                                <option value="<?= $i; ?>"><?= $i; ?></option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group form-group-select-plus">
                                        <label>Rooms</label>
                                        <div class="btn-group btn-group-select-num" data-toggle="buttons">
                                            <label class="btn btn-primary active">
                                                <input type="radio" name="rooms" value="1" />1</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="rooms" value="2" />2</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="rooms" value="3" />3</label>
                                            <label class="btn btn-primary">
                                                <input type="radio" name="rooms" value="noRadio"/>3+</label>
                                        </div>
                                        <select name="roomsSelect" class="form-control hidden">
                                            <?php for($i=1; $i<=6; $i++): ?>
                                                <option value="<?= $i; ?>"><?= $i; ?></option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <input type="hidden" name="hid" value="<?= $hotel->getId(); ?>">
                                    <input type="submit" name="checkAvailability" value="Check availability"
                                           id="checkAvailabilitySubmit"
                                           class="btn btn-primary">
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="gap gap-small"></div>

                </div>
                <div class="col-md-3">
                    <h4>About the Hotel</h4>
                    <p class="mb30">
                        <?= $hotel->getDescEn(); ?>
                    </p>
                </div>
            </div>


            <div class="row">
                <div class="col-md-9">

                    <h4>Hotels Near <?php echo $hotel->getName(); ?></h4>

                    <ul class="booking-list">
                        <?php for ($i=0; $i < 9; $i++): ?>
                            <?php if (isset($hotel->getRelatedHotels()[$i]) && ($relatedHotel = $hotel->getRelatedHotels()[$i])): ?>
                                <li>
                                    <a class="booking-item"
                                       href="<?= $hotel->getRelatedHotels()[$i]->getBookingHotelUrl(); ?>"
                                       target="_blank">
                                        <div class="row">
                                            <div class="col-md-3" style="height: 130px; overflow: hidden;">
                                                <img src="<?= $relatedHotel->getImages()[0]->getSrc(); ?>"
                                                    <?php if (! $relatedHotel->getImages()[0]->isCached()): ?>
                                                        data-no-cache-image="1"
                                                    <?php endif; ?>
                                                     data-hotel-id="<?= $relatedHotel->getId(); ?>" data-city-unique="<?= $hotel->getCityUnique(); ?>"
                                                     alt="<?= $relatedHotel->getName(); ?> photo" title="hotel PORTO BAY RIO INTERNACIONAL rooftop pool" />
                                            </div>
                                            <div class="col-md-5">
                                                <h5 class="booking-item-title"><?= $relatedHotel->getName(); ?></h5>
                                                <p class="text-small"><?= $relatedHotel->getDescEn(); ?></p>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </ul>
                </div>
                <div class="col-md-3">


                    <a href="<?= $routeHelper->getHotelCheckAvailabilityUrl($hotel->getName(), $hotel->getId()); ?>" target="_blank">
                        <button class="btn btn-primary"
                        style="width: 100%;margin-bottom: 20px;height: 60px;font-weight: bold;">
                            Book NOW on Booking.com
                        </button>
                    </a>

                    <ins class="bookingaff"
                         data-aid="1596221" data-target_aid="1596221" data-prod="banner" data-width="100%" data-height="60" data-lang="xu">
                        <!-- Anything inside will go away once widget is loaded. -->
                        <a href="//www.booking.com?aid=1596221">Booking.com</a>
                    </ins>
                    <script type="text/javascript">
                        (function(d, sc, u) {
                            var s = d.createElement(sc), p = d.getElementsByTagName(sc)[0];
                            s.type = 'text/javascript';
                            s.async = true;
                            s.src = u + '?v=' + (+new Date());
                            p.parentNode.insertBefore(s,p);
                        })(document, 'script', '//aff.bstatic.com/static/affiliate_base/js/flexiproduct.js');
                    </script>

                    <h4 style="margin-top: 20px;">Hotel Facilities</h4>

                    <div id="hotelInfo_facilities">
                        <?php echo $hotelInfo->getFacilities(); ?>
                    </div>
                </div>
            </div>

        </div>
        <div class="gap gap-small"></div>
    </div>


<?php require_once $this->getTemplatePath() . 'includes/scripts.phtml'; ?>


    <script>
        var nonCachedImages = new Array();
        $('[data-no-cache-image]').each(function (index) {
            var $this = $(this);
            nonCachedImages.push({
                src: $this.attr('src'),
                hotelId: $this.data('hotel-id'),
                cityUnique: $this.data('city-unique')
            });
        });

        if (nonCachedImages.length >= 1) {
            $.post(
                "<?= $routeHelper->getCacheImagesUrl(); ?>",
                {
                    nonCachedImages: nonCachedImages
                }
            ).done(function (data) {
            });
        }
    </script>

    <?php if ($hotelInfo instanceof \Infotrip\HotelParser\Entity\NullHotelInfo): ?>
    <script>

        $.ajax({
            type: 'POST',
            url: '<?= $routeHelper->getCacheHotelUrl(); ?>',
            data: {
                hid: <?= $hotel->getId(); ?>
            },
            success: function (data) {

                $('.bg-mask').remove();

                if (data["externalHotelInfo"]) {
                    for (var key in data["externalHotelInfo"]) {
                        var $placeholderElm = $('#hotelInfo_' + key);
                        var $placeholderIterator = $('#hotelInfo' + key);

                        if ($placeholderElm.length) {
                            $placeholderElm.html(
                                data["externalHotelInfo"][key]
                            );
                        }

                        if(key === 'starsScore') {
                            for (var i=1; i<=data["externalHotelInfo"][key]; i++ ) {
                                $placeholderIterator.append('<i class="fa fa-star"></i>')
                            }
                        } else if(key === 'reviewScores') {
                            if (data["externalHotelInfo"][key].length) {
                                for (var i=0; i<data["externalHotelInfo"][key].length; i++) {
                                    var label = data["externalHotelInfo"][key][i]["label"];
                                    var score = data["externalHotelInfo"][key][i]["score"];
                                    var percent = data["externalHotelInfo"][key][i]["percent"];

                                    $placeholderIterator.append(
                                        '<li><div class="booking-item-raiting-list-title">'+label+'</div><div class="booking-item-raiting-list-bar"><div style="width:'+percent+'%;"></div></div><div class="booking-item-raiting-list-number">'+score+'</div></li>'
                                    )
                                }
                            }
                        } else if(key === 'reviewFunctionsScores') {
                            if (data["externalHotelInfo"][key].length) {
                                for (var i=0; i<data["externalHotelInfo"][key].length; i++) {
                                    var label = data["externalHotelInfo"][key][i]["label"];
                                    var starBase5 = data["externalHotelInfo"][key][i]["starBase5"];

                                    var html = '<li><div class="booking-item-raiting-list-title">'+label+'</div><ul class="icon-group booking-item-rating-stars">'
                                    for (var j=1; j<=starBase5; j++) {
                                        html += '<li><i class="fa fa-smile-o"></i></li>';
                                    }
                                    html += '</ul></li>';
                                    $placeholderIterator.append(html)
                                }
                            }
                        } else if(key === 'hotelComments') {
                            if (data["externalHotelInfo"][key].length) {
                                for (var i=0; i<data["externalHotelInfo"][key].length; i++) {
                                    var reviewComment = data["externalHotelInfo"][key][i]["reviewComment"];
                                    var reviewUser = data["externalHotelInfo"][key][i]["reviewUser"];
                                    var reviewUserLocation = data["externalHotelInfo"][key][i]["reviewUserLocation"];

                                    $placeholderIterator.append(
                                        '<li><div class="row"><div class="col-md-2"><div class="booking-item-review-person"><p class="booking-item-review-person-name">'+reviewUser+'</p><p class="booking-item-review-person-loc">'+reviewUserLocation+'</p></div></div><div class="col-md-10"><div class="booking-item-review-content"><p>'+reviewComment+'</p></div></div></div></li>'
                                    )
                                }
                            }
                        }
                    }

                    <?php if (
                        (count($hotel->getImages()) <= 1)
                    ): ?>
                    if(key === 'images') {
                        if (data["externalHotelInfo"][key].length) {
                            // get the API fotorama object.
                            var fotorama = $('#hotelImageGallery').data('fotorama');
                            for (var i=0; i<data["externalHotelInfo"][key].length; i++) {
                                var src = data["externalHotelInfo"][key][i]["src"];
                                fotorama.push({img: src, thumb: src});
                            }
                        }
                    }
                    <?php endif; ?>

                }
            },
            dataType: 'json',
            beforeSend: function (jqXHT, settings) {
            }
        });


    </script>
    <?php endif; ?>

    <script>
        if ($('#map-canvas').length) {
            var map,
                service;


                    var directionsDisplay = new google.maps.DirectionsRenderer();
                    var directionsService = new google.maps.DirectionsService();

                    // arrays to hold copies of the markers and html used by the side_bar
                    // because the function closure trick doesnt work there
                    var gmarkers = [];
                    var htmls = [];

                    // arrays to hold variants of the info window html with get direction forms open
                    var to_htmls = [];
                    var from_htmls = [];

                    var latlng = new google.maps.LatLng('<?= $hotel->getLatitude(); ?>', '<?= $hotel->getLongitude(); ?>');
                    var myOptions = {
                        zoom: 16,
                        center: latlng,
                        mapTypeId: google.maps.MapTypeId.ROADMAP,
                        scrollwheel: false
                    };

                    map = new google.maps.Map(document.getElementById("map-canvas"), myOptions);

                    var infowindow = new google.maps.InfoWindow({
                        size: new google.maps.Size(150, 50)
                    });

                    var marker = new google.maps.Marker({
                        position: latlng,
                        map: map,
                        label: '<?= $hotel->getName(); ?>',
                        title: '<?= $hotel->getName(); ?>',
                        animation: google.maps.Animation.DROP,
                    });
                    marker.setMap(map);

                    directionsDisplay.setMap(map);
                    directionsDisplay.setPanel(document.getElementById("directionsPanel"));

                    var i = gmarkers.length;

                    // The info window version with the "to here" form open
                    to_htmls[i] = html + '<br>Directions: <b>To here<\/b> - <a href="javascript:fromhere(' + i + ')">From here<\/a>' +
                        '<br>Start address:<form action="javascript:getDirections()">' +
                        '<input type="text" SIZE=40 MAXLENGTH=40 name="saddr" id="saddr" value="" /><br>' +
                        '<INPUT value="Get Directions" TYPE="button" onclick="getDirections()"><br>' +
                        'Walk <input type="checkbox" name="walk" id="walk" /> &nbsp; Avoid Highways <input type="checkbox" name="highways" id="highways" />' +
                        '<input type="hidden" id="daddr" value="' + latlng.lat() + ',' + latlng.lng() +
                        '"/>';
                    // The info window version with the "from here" form open
                    from_htmls[i] = html + '<br>Directions: <a href="javascript:tohere(' + i + ')">To here<\/a> - <b>From here<\/b>' +
                        '<br>End address:<form action="javascript:getDirections()">' +
                        '<input type="text" SIZE=40 MAXLENGTH=40 name="daddr" id="daddr" value="" /><br>' +
                        '<INPUT value="Get Directions" TYPE="SUBMIT"><br>' +
                        'Walk <input type="checkbox" name="walk" id="walk" /> &nbsp; Avoid Highways <input type="checkbox" name="highways" id="highways" />' +
                        '<input type="hidden" id="saddr" value="' + latlng.lat() + ',' + latlng.lng() +
                        '"/>';
                    // The inactive version of the direction info
                    var html = marker.getTitle() + '<br>Directions: <a href="javascript:tohere(' + i + ')">To here<\/a> - <a href="javascript:fromhere(' + i + ')">From here<\/a>';
                    var contentString = html;

                    google.maps.event.addListener(marker, 'click', function() {
                        map.setZoom(15);
                        map.setCenter(marker.getPosition());
                        infowindow.setContent(contentString);
                        infowindow.open(map, marker);
                    });
                    // save the info we need to use later for the side_bar
                    gmarkers.push(marker);
                    htmls[i] = html;

                    $('a[href="#google-map-tab"]').on('shown.bs.tab', function(e) {
                        google.maps.event.trigger(map, 'resize');
                        map.setCenter(latlng);
                    });

                    // ===== request the directions =====
                    function getDirections() {
                        // ==== Set up the walk and avoid highways options ====
                        var request = {};
                        if (document.getElementById("walk").checked) {
                            request.travelMode = google.maps.DirectionsTravelMode.WALKING;
                        } else {
                            request.travelMode = google.maps.DirectionsTravelMode.DRIVING;
                        }

                        if (document.getElementById("highways").checked) {
                            request.avoidHighways = true;
                        }
                        // ==== set the start and end locations ====
                        var saddr = document.getElementById("saddr").value;
                        var daddr = document.getElementById("daddr").value;

                        request.origin = saddr;
                        request.destination = daddr;
                        directionsService.route(request, function(response, status) {
                            if (status == google.maps.DirectionsStatus.OK) {
                                directionsDisplay.setDirections(response);
                            } else alert("Directions not found:" + status);
                        });
                    }


                    // This function picks up the click and opens the corresponding info window
                    function myclick(i) {
                        google.maps.event.trigger(gmarkers[i], "click");
                    }

                    // functions that open the directions forms
                    function tohere(i) {
                        // gmarkers[i].openInfoWindowHtml(to_htmls[i]);
                        infowindow.setContent(to_htmls[i]);
                        infowindow.open(map, gmarkers[i]);
                    }

                    function fromhere(i) {
                        // gmarkers[i].openInfoWindowHtml(from_htmls[i]);
                        infowindow.setContent(from_htmls[i]);
                        infowindow.open(map, gmarkers[i]);
                    }





        }
    </script>

    <script>
        $('#checkInDateInput').datepicker()
            .on('changeDate', function(e) {
                $(this).datepicker('hide');
                $('#checkOutDateInput').datepicker('show');
            });

        $('#checkOutDateInput').datepicker()
            .on('changeDate', function(e) {
                $(this).datepicker('hide');
            });
    </script>


<?php require_once $this->getTemplatePath() . 'includes/footer.phtml'; ?>


