<?php

    /** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
    $routeHelper = $viewHelpers['routeHelper'];

    require_once $this->getTemplatePath() . 'includes/header.phtml';
?>

<div class="global-wrap">

    <div class="container">
        <h1 class="page-title">About Us</h1>
    </div>



    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <p class="text-bigger">Felis turpis nostra arcu tempus rutrum hac ullamcorper torquent volutpat pellentesque adipiscing ut elementum sollicitudin sodales congue quam rutrum habitant accumsan elit scelerisque accumsan proin varius purus scelerisque taciti nam</p>
                <p class="text-bigger">Venenatis diam malesuada faucibus euismod congue eleifend ultricies bibendum augue dapibus nostra diam amet tincidunt commodo ullamcorper lorem maecenas nibh</p>
            </div>
        </div>
        <div class="gap"></div>
    </div>
    <div class="bg-holder">
        <div class="bg-parallax" style="background-image:url(img/ancient-architecture-bridge-753337.jpg);"></div>
        <div class="bg-mask"></div>
        <div class="bg-holder-content">
            <div class="container">
                <div class="gap gap-big text-white">
                    <div class="row">
                        <div class="col-md-10">
                            <h2>Work hard. Play hard.</h2>
                            <p class="text-bigger">Scelerisque ornare ante pellentesque id ad eget volutpat consequat aptent lacus penatibus consectetur vivamus magnis ornare venenatis mattis rhoncus interdum quam tempor commodo ultrices augue risus senectus ornare aliquam leo rutrum nam duis nisi fringilla convallis praesent libero faucibus fermentum convallis pretium aptent nisl morbi odio justo vel nascetur tristique pulvinar senectus etiam quam taciti dignissim etiam tincidunt cras molestie</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="gap"></div>
        <h2>Our Approach</h2>
        <div class="row">
            <div class="col-md-8">
                <p class="text-bigger">Cubilia gravida mus senectus donec consectetur dis ac vel quis a suscipit potenti purus aptent nibh gravida aliquet vestibulum varius dictum consectetur semper consectetur at varius donec sociis habitasse vivamus eget faucibus tempus donec lorem etiam volutpat blandit aliquam varius molestie nibh mattis adipiscing sodales dictumst volutpat quam rhoncus sodales</p>
            </div>
        </div>

        <div class="gap"></div>
    </div>

<?php require_once $this->getTemplatePath() . 'includes/scripts.phtml'; ?>
<?php require_once $this->getTemplatePath() . 'includes/footer.phtml'; ?>


