<?php

    /** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
    $routeHelper = $viewHelpers['routeHelper'];

    require_once $this->getTemplatePath() . 'includes/header.phtml';
?>

<div class="global-wrap">

    <div class="container">
        <h1 class="page-title">About Us</h1>
    </div>



    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <p class="text-bigger">
                    <a href="<?= $routeHelper->getHomepageUrl(); ?>">Infotrip.org</a>
                    is an online hotel booking service with properties in 225 countries worldwide. We offer over a million and a half different listings covering all types of accommodation ranging from hotels and hostels to apartments and more, all at affordable prices. We aim to make your travel dreams come true.
                </p>
            </div>
        </div>
        <div class="gap"></div>
    </div>

<?php require_once $this->getTemplatePath() . 'includes/scripts.phtml'; ?>
<?php require_once $this->getTemplatePath() . 'includes/footer.phtml'; ?>


