<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-start.phtml';
/** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
?>


    <div class="row">
        <div class="col-md-12">
            <div class="box-inn-sp">
                <div class="inn-title">
                    <h4>Associate hotels</h4>
                </div>
                <div class="tab-inn">

                    <?php if (isset($successMessage) && $successMessage): ?>
                        <div class="alert alert-success" role="alert">
                            <?= $successMessage; ?>
                        </div>
                    <?php endif; ?>

                    <?php if (isset($errorMessage) && $errorMessage): ?>
                        <div class="alert alert-danger" role="alert">
                            <?= $errorMessage; ?>
                        </div>
                    <?php endif; ?>

                    <ul>
                        <li>
                            <a href="<?= $routeHelper->getAdminRootAgodaAssociateHotelsUrl($level = 1); ?>">
                                Execute - <?= \Infotrip\Service\Agoda\Service\AgodaAssociater\AssociaterLevel1::ASSOC_NAME; ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $routeHelper->getAdminRootAgodaAssociateHotelsUrl($level = 2); ?>">
                                Execute - <?= \Infotrip\Service\Agoda\Service\AgodaAssociater\AssociaterLevel2::ASSOC_NAME; ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $routeHelper->getAdminRootAgodaAssociateHotelsUrl($level = 3); ?>">
                                Execute - <?= \Infotrip\Service\Agoda\Service\AgodaAssociater\AssociaterLevel3::ASSOC_NAME; ?>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
    </div>

<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-end.phtml';
?>