<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-start.phtml';
?>


    <div class="row">
        <div class="col-md-12">
            <div class="box-inn-sp">
                <div class="inn-title">
                    <h4>Associate hotels</h4>
                </div>
                <div class="tab-inn">

                    <?php if (isset($successMessage) && $successMessage): ?>
                        <div class="alert alert-success" role="alert">
                            <?= $successMessage; ?>
                        </div>
                    <?php endif; ?>

                    <?php if (isset($errorMessage) && $errorMessage): ?>
                        <div class="alert alert-danger" role="alert">
                            <?= $errorMessage; ?>
                        </div>
                    <?php endif; ?>

                    aici

                </div>
            </div>
        </div>
    </div>

<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-end.phtml';
?>