<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-start.phtml';
?>


    <div class="row">
        <div class="col-md-12">
            <div class="box-inn-sp">
                <div class="inn-title">
                    <h4>Import hotels</h4>
                </div>
                <div class="tab-inn">

                    <?php if (isset($successMessage) && $successMessage): ?>
                        <div class="alert alert-success" role="alert">
                            <?= $successMessage; ?>
                        </div>
                    <?php endif; ?>

                    <?php if (isset($errorMessage) && $errorMessage): ?>
                        <div class="alert alert-danger" role="alert">
                            <?= $errorMessage; ?>
                        </div>
                    <?php endif; ?>

                    <form method="post"
                          enctype="multipart/form-data"
                          action="<?= $routeHelper->getAdminRootAgodaImportHotelsProcessUrl(); ?>">
                        <div class="row">
                            <div class="input-field col s12">
                                <input id="importFile" name="importFile" required
                                       type="file" value="" class="validate">
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input type="submit" class="waves-effect waves-light btn-large" value="Import">
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-end.phtml';
?>