
<?php
    $routeHelper = $viewHelpers['routeHelper'];
    require_once $this->getTemplatePath() . 'hotelOwners/admin/includes/header.phtml';
    require_once $this->getTemplatePath() . 'hotelOwners/admin/includes/top.phtml';

?>

<!--== BODY CONTNAINER ==-->
<div class="container-fluid sb2">
    <div class="row">


<?php
    require_once $this->getTemplatePath() . 'hotelOwners/admin/includes/left-menu.phtml';
?>

        <div class="sb2-2">

<?php
    require_once $this->getTemplatePath() . 'hotelOwners/admin/includes/breadcrumb.phtml';
?>

            <div class="sb2-2-3">
