<?php
/** @var $randomUrlsHelper \Infotrip\ViewHelpers\RandomUrlsHelper */
$randomUrlsHelper = $viewHelpers['randomUrlsHelper'];
?>

<footer id="main-footer">
    <div class="container">
        <div class="row row-wrap">
            <div class="col-md-3">
                <a class="logo" href="/index.html">
                    <img src="/img/logo-invert.png" alt="Image Alternative text" title="Image Title" />
                </a>
                <p class="mb20">Booking, reviews and advices on hotels, resorts, flights, vacation rentals, travel packages, and lots more!</p>
                <ul class="list list-horizontal list-space">
                    <li>
                        <a class="fa fa-facebook box-icon-normal round animate-icon-bottom-to-top" href="https://www.facebook.com/InfoTriporg-416430748761127/" target="_blank"></a>
                    </li>
                    <li>
                        <a class="fa fa-twitter box-icon-normal round animate-icon-bottom-to-top" href="https://twitter.com/InfotripO" target="_blank"></a>
                    </li>
                    <li>
                        <a class="fa fa-google-plus box-icon-normal round animate-icon-bottom-to-top" href="https://plus.google.com/u/0/113899573542661210274" target="_blank"></a>
                    </li>
                    <li>
                        <a class="fa fa-instagram box-icon-normal round animate-icon-bottom-to-top" href="https://www.instagram.com/infotriporg/" target="_blank"></a>
                    </li>
                    <li>
                        <a class="fa fa-pinterest box-icon-normal round animate-icon-bottom-to-top" href="https://www.pinterest.com/infotripo/" target="_blank"></a>
                    </li>
                </ul>
            </div>

            <div class="col-md-3">
                <h5>Resources</h5>
                <ul class="list list-footer">
                    <li><a href="<?= $routeHelper->getAboutUrl(); ?>">About infotrip.org</a></li>
                    <li><a href="<?= $routeHelper->getTermsUrl(); ?>">Terms & Conditions</a></li>
                    <li><a href="<?= $routeHelper->getPrivacyUrl(); ?>">Cookies & Privacy</a></li>
                    <li><a href="<?= $routeHelper->getHotelOwnersUrl(); ?>">For hotel owners</a></li>
                    <li><a href="<?= $routeHelper->getContactUrl(); ?>">Contact us</a></li>
                </ul>
            </div>

            <div class="col-md-3">
                <h5>Hotels in country</h5>
                <ul class="list list-footer">
                <?php foreach ($randomUrlsHelper->getRandomCountryUrls() as $data): ?>
                    <li><a href="<?= $data['url']; ?>">
                            <?= $data['label']; ?>
                        </a></li>
                <?php endforeach; ?>
                </ul>
            </div>

            <div class="col-md-3">
                <h5>Hotels in city</h5>
                <ul class="list list-footer">
                    <?php foreach ($randomUrlsHelper->getRandomCityUrls() as $data): ?>
                        <li><a href="<?= $data['url']; ?>">
                                <?= $data['label']; ?>
                            </a></li>
                    <?php endforeach; ?>
                </ul>
            </div>

        </div>
    </div>
</footer>


</div>

<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
    window.addEventListener("load", function(){
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": "#237afc"
                },
                "button": {
                    "background": "#fff",
                    "text": "#237afc"
                }
            },
            "content": {
                "message": "Infotrip.org uses both its own and third-party cookies for technical, analytical, and marketing purposes.  If you continue to use this site we will assume that you are happy with it. Consult our cookie statement -&gt;",
                "href": "http://infotrip.org/cookies-and-privacy"
            }
        })});
</script>

</body>

</html>
