<footer id="main-footer">
    <div class="container">
        <div class="row row-wrap">
            <div class="col-md-3">
                <a class="logo" href="/index.html">
                    <img src="/img/logo-invert.png" alt="Image Alternative text" title="Image Title" />
                </a>
                <p class="mb20">Booking, reviews and advices on hotels, resorts, flights, vacation rentals, travel packages, and lots more!</p>
                <ul class="list list-horizontal list-space">
                    <li>
                        <a class="fa fa-facebook box-icon-normal round animate-icon-bottom-to-top" href="/#"></a>
                    </li>
                    <li>
                        <a class="fa fa-twitter box-icon-normal round animate-icon-bottom-to-top" href="/#"></a>
                    </li>
                    <li>
                        <a class="fa fa-google-plus box-icon-normal round animate-icon-bottom-to-top" href="/#"></a>
                    </li>
                    <li>
                        <a class="fa fa-linkedin box-icon-normal round animate-icon-bottom-to-top" href="/#"></a>
                    </li>
                    <li>
                        <a class="fa fa-pinterest box-icon-normal round animate-icon-bottom-to-top" href="/#"></a>
                    </li>
                </ul>
            </div>

            <div class="col-md-3">

            </div>
            <div class="col-md-2">
                <ul class="list list-footer">
                    <li><a href="<?= $routeHelper->getAboutUrl(); ?>">About infotrip.org</a></li>
                    <li><a href="<?= $routeHelper->getTermsUrl(); ?>">Terms & Conditions</a></li>
                    <li><a href="<?= $routeHelper->getPrivacyUrl(); ?>">Cookies & Privacy</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <h4>Have Questions?</h4>
                <h4 class="text-color">+1-202-555-0173</h4>
                <h4><a href="/#" class="text-color">support@traveler.com</a></h4>
                <p>24/7 Dedicated Customer Support</p>
            </div>

        </div>
    </div>
</footer>


</div>
</body>

</html>
