<!DOCTYPE HTML>
<html>

<head>

    <?php require_once $this->getTemplatePath() . 'includes/meta.phtml'; ?>

    <!-- GOOGLE FONTS -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,600' rel='stylesheet' type='text/css'>
    <!-- /GOOGLE FONTS -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/font-awesome.css">
    <link rel="stylesheet" href="/css/icomoon.css">
    <link rel="stylesheet" href="/css/styles.css">
    <link rel="stylesheet" href="/css/mystyles.css?m=2">
    <script src="/js/modernizr.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-120798669-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-120798669-1');
    </script>

</head>

<body>

<!-- FACEBOOK WIDGET -->
<div id="fb-root"></div>
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<!-- /FACEBOOK WIDGET -->
<div class="global-wrap">
    <header id="main-header">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <a class="logo" href="<?= $routeHelper->getHomepageUrl(); ?>">
                            <img src="/img/logo-invert.png" alt="Homepage" title="Homepage" />
                        </a>
                    </div>
                    <div class="col-md-3 col-md-offset-2">
                        <form method="get"
                              action="<?= $routeHelper->getHotelsSearchUrl(); ?>"
                                class="main-header-search">
                            <div class="form-group form-group-icon-left">
                                <i class="fa fa-search input-icon"></i>
                                <input name="term" type="text" class="form-control">
                            </div>
                        </form>
                    </div>
                    <div class="col-md-4">
                        <div class="top-user-area clearfix">
                            <ul class="top-user-area-list list list-horizontal list-border">

                                <li><a href="<?= $routeHelper->getHotelOwnerLoginRegisterUrl(); ?>">Sign in</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="nav">
                <ul class="slimmenu" id="slimmenu">
                    <li><a href="<?= $routeHelper->getHomepageUrl(); ?>">Home</a></li>
                    <li><a style="cursor: pointer;">Continents</a>
                        <ul>
                            <li><a href="<?= $routeHelper->getListCountriesUrl('Europe'); ?>">Europe</a>
                            <li><a href="<?= $routeHelper->getListCountriesUrl('Asia'); ?>">Asia</a>
                            <li><a href="<?= $routeHelper->getListCountriesUrl('North America'); ?>">North America</a>
                            <li><a href="<?= $routeHelper->getListCountriesUrl('South America'); ?>">South America</a>
                            <li><a href="<?= $routeHelper->getListCountriesUrl('Central America'); ?>">Central America</a>
                            <li><a href="<?= $routeHelper->getListCountriesUrl('Africa'); ?>">Africa</a>
                            <li><a href="<?= $routeHelper->getListCountriesUrl('Middle East'); ?>">Middle East</a>
                            <li><a href="<?= $routeHelper->getListCountriesUrl('Australia & Pacific'); ?>">Australia & Pacific</a>
                            <li><a href="<?= $routeHelper->getListCountriesUrl('Caribbean'); ?>">Caribbean</a>
                        </ul>
                    </li>
                    <li><a href="<?= $routeHelper->getContactUrl(); ?>">Contact</a></li>
                </ul>
            </div>
        </div>
    </header>