<?php
/** @var $hotelOwnerUser \Infotrip\Domain\Entity\HotelOwnerUser */
/** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
/** @var $adminUiService \Infotrip\Utils\UI\Admin\Admin */
?>
<div class="sb2-1">
    <!--== USER INFO ==-->
    <div class="sb2-12">
        <ul>
            <li><img src="admin/images/default_profile.png" alt="">
            </li>
            <li>
                <h5>
                    <?= $hotelOwnerUser->getEmail(); ?>
                    <span>
                        hotel owner
                    </span>
                </h5>
            </li>
            <li></li>
        </ul>
    </div>
    <!--== LEFT MENU ==-->
    <div class="sb2-13">


        <ul class="collapsible" data-collapsible="accordion">
            <?php foreach ($adminUiService->getAdminMenu()->getMenu() as $adminMenu): ?>
            <li>
                <?php if ($adminMenu->isHasSubmenu()): ?>
                <a href="javascript:void(0)" class="collapsible-header <?php if($adminMenu->isActive()) :?>active<?php endif; ?>"><i class="fa <?= $adminMenu->getCssClass(); ?>" aria-hidden="true"></i> <?= $adminMenu->getLabel(); ?></a>
                <div class="collapsible-body left-sub-menu">
                    <ul>
                    <?php foreach ($adminMenu->getSubmenu() as $submenu): ?>
                            <li>
                                <a class="<?php if($submenu->isActive()) :?>menu-active<?php endif; ?>"
                                    href="<?= $submenu->getLink(); ?>"> <?= $submenu->getLabel(); ?></a>
                            </li>
                    <?php endforeach; ?>
                    </ul>
                </div>
                <?php else: ?>
                        <a  class="<?php if($adminMenu->isActive()) :?>menu-active<?php endif; ?>"
                            href="<?= $adminMenu->getLink(); ?>"><i class="fa <?= $adminMenu->getCssClass(); ?>" aria-hidden="true"></i> <?= $adminMenu->getLabel(); ?></a>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>