<?php
/** @var $hotelOwnerUser \Infotrip\Domain\Entity\HotelOwnerUser */
/** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
?>
<div class="sb2-1">
    <!--== USER INFO ==-->
    <div class="sb2-12">
        <ul>
            <li><img src="admin/images/default_profile.png" alt="">
            </li>
            <li>
                <h5>
                    <?= $hotelOwnerUser->getEmail(); ?>
                    <span>
                        hotel owner
                    </span>
                </h5>
            </li>
            <li></li>
        </ul>
    </div>
    <!--== LEFT MENU ==-->
    <div class="sb2-13">
        <ul class="collapsible" data-collapsible="accordion">
            <li><a href="javascript:void(0)" class="collapsible-header active"><i class="fa fa-h-square" aria-hidden="true"></i> Hotels</a>
                <div class="collapsible-body left-sub-menu">
                    <ul>
                        <li><a href="hotel-all.html" class="menu-active">All Hotels</a>
                        </li>
                        <li><a href="hotel-add.html">Add New Hotel</a>
                        </li>
                    </ul>
                </div>
            </li>

            <li>
                <a href="<?= $routeHelper->getHotelOwnerAdminSocialMediaUrl(); ?>"><i class="fa fa-plus-square-o" aria-hidden="true"></i> Social Media</a>
            </li>
            <li>
                <a href="<?= $routeHelper->getHotelOwnerAdminLogoutUrl(); ?>"><i class="fa fa-sign-in" aria-hidden="true"></i> Logout</a>
            </li>
        </ul>
    </div>
</div>