<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-start.phtml';
/** @var $users \Infotrip\Domain\Entity\AuthUser[] */
?>


<div class="row">
    <div class="col-md-12">
        <div class="box-inn-sp">
            <div class="inn-title">
                <h4>Account Settings</h4>
            </div>
            <div class="tab-inn">

                <?php if (isset($successMessage) && $successMessage): ?>
                    <div class="alert alert-success" role="alert">
                        <?= $successMessage; ?>
                    </div>
                <?php endif; ?>

                <?php if (isset($errorMessage) && $errorMessage): ?>
                    <div class="alert alert-danger" role="alert">
                        <?= $errorMessage; ?>
                    </div>
                <?php endif; ?>

                <form method="post" action="<?= $routeHelper->getAdminRootAssociateHotelsProcessUrl(); ?>">
                    <div class="row">
                        <div class="input-field col s12">
                            <select name="userId" id="userId" class="validate" required>
                                <option value="">Choose...</option>
                                <?php foreach ($users as $user): ?>
                                    <option value="<?= $user->getId(); ?>"><?= $user->getEmail(); ?></option>
                                <?php endforeach; ?>
                            </select>
                            <label for="userId">User email</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <input id="hotelIds" name="hotelIds" required
                                   type="text" value="" class="validate">
                            <label for="hotelIds">Hotel ids (Comma separated)</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <input type="submit" class="waves-effect waves-light btn-large" value="Save">
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-end.phtml';
?>