<?php

    /** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
    $routeHelper = $viewHelpers['routeHelper'];

    require_once $this->getTemplatePath() . 'includes/header.phtml';
?>

<div class="global-wrap">

    <div class="container">
        <h1 class="page-title">Cookies & Privacy</h1>
    </div>




    <div class="container">
        <div class="row">
            <div class="col-md-8">

                <h3>Privacy Policy</h3>
                <p class="text-bigger">
                We seek to take advantage of all available means to ensure the security and transparency of the Infotrip.org information retrieval service, which provides information about services for booking temporary accommodations. The Service Owner hereby informs users about what user information can be accessed by the Service as well as how the information that is obtained by the Service is used.
                </p>
                <h4>Collection and storage of information</h4>
                <p class="text-bigger">
                    All kinds of data are collected and processed in order to provide users with quality services in accordance with the <a href="<?= $routeHelper->getTermsUrl(); ?>">Service Terms and Conditions of Use</a>.<br>
                Data is stored on secure servers. Infotrip.org utilizes appropriate technical and organizational measures to ensure the security of data, including access control, firewalls, encryption, HTTPS (HyperText Transfer Protocol Secure), and SSL (Secure Sockets Layer) for data transmission. Infotrip.org does not purposely collect information that can be used to identify (determine) specific individuals who are Service users. At the same time, Infotrip.org may acquire certain information about users as they use the Service and as a result of their individual actions to take advantage of Service functionality. The list of this information and the reason why it is collected are detailed below.
                </p>
                <h4>Information that is directly provided by users</h4>
                Infotrip.org allows the User to subscribe to a website newsletter. The website uses the user-provided e-mail address exclusively to provide information about prices for accommodations at selected venues and to send out a newsletter. The User may at any time unsubscribe from the newsletter by clicking on the appropriate "Unsubscribe" link, which can be found in all e-mails that are sent to the user’s subscribed e-mail address.
                The Infotrip.org software allows users to register an account on the website in order to use the Service for personal purposes. Users can log into the website Infotrip.org using social network accounts (Facebook, Google, Twitter). In this situation the service can obtain information about the user’s name as specified in their social media account profile. This information can be used by the Service for the following purposes:
                <ul>
                    <li>to allow the User to log into the Infotrip.org websites.This is done to provide Infotrip.org users with special offers from Service partners;</li>
                    <li>to offer retargeting, i.e., displaying Google Adsense ads to users when they visit other sites;</li>
                    <li>and to allow the user the ability to personally manage site features (i.e., the User can select and save the particular service functions and settings that they find useful).</li>
                </ul>
                The User is allowed to use the Service software to submit data that is required to purchase services directly on the Infotrip.org website or mobile app, including credit card numbers, guest names, phone numbers and e-mail addresses, and to send this information to a third party provider that sells temporary accommodation services in order to complete the booking. In this case the transmission of user data to third parties must be authorized and carried out directly by the User via a secure connection. In this case Infotrip.org does not receive any credit card data. However, it is able to obtain confirmation that a reservation was successfully made as well as the name and e-mail address that were specified by the user. The information that is obtained by the Service in this way is used by the Service for the following purposes:
                <ul>
                    <li>Improving the quality of the Service,</li>
                    <li>Providing the User with support in the event of a dispute with a Service partner,</li>
                    <li>Allowing Service employees to contact the User about issues related to booking.</li>
                </ul>
                <h4>Automatically collected information</h4>
                Infotrip.org automatically stores information sent by the user’s browser when they visit the site. This information includes the page request, IP address, browser type, browser language, as well as the date and time when the page was loaded. When accessing the service from a mobile device, Infotrip.org may collect data that identifies your mobile device as well as its specific settings and characteristics. The information that is collected in this way is used to analyze and maintain the quality of the Infotrip.org service.
                <h4>Cookie files</h4>
                Cookies are small text files that are typically stored on the user’s computer until the end of the session, i.e., until the user finishes working in the browser. However, sometimes they are stored for longer periods of time.
                When the User visits the Infotrip.org website, it sends one or more cookie files to the user’s computer or another device.
                The cookie files are used:
                <ul>
                    <li>to simplify the use of the website and to improve the quality of the services provided in order, for example, to save user settings and to automatically fill in places of interest where the user wishes to book temporary accommodations and calendar search dates;</li>
                    <li>to keep track of when users make reservations at Infotrip.org partner companies (agencies, reservation systems, hotels, inns, hostels, guest houses, etc.). After the user selects a venue that they are interested in and clicks "Book", the site redirects them to the website of the Infotrip.org partner where the temporary accommodations can be booked. Infotrip.org does not collect any personal data about users who complete a transaction on a partner site. Our service is only sent statistical data on the total number of bookings and the prices for the transactions. This information is used to determine the referral fee that is due to Infotrip.org;</li>
                    <li>for analysis to better target advertising.</li>
                </ul>
                <h4>Use of Cookies and other tools for promotional purposes</h4>
                The Infotrip.org website uses third party services to track usage statistics, information about advertising campaign conversions, and other data. Infotrip.org does not use these services and tools to collect data on specific users. It only uses general statistics about visitation, the effectiveness of the website, and the effectiveness of advertising campaigns. Below is a list of additional third-party services that Infotrip.org uses as well as links to the privacy policies of these services.<br><br>
                Google Analytics and Adwords, the analytics web service of Google Inc. ("Google")<br><br>
                Google Analytics is a free web analytics service from Google, which allows website owners to learn how users interact with their pages. The service collects information anonymously. The company uses its own cookie files to track visitor activities on the website in Google Analytics. They allow you to find out if the user visited this web resource before, the last page that they came from, and how much time they spent there.<br><br>
                Infotrip.org uses the <a href="https://marketingplatform.google.com/about/" target="_blank">Google Analytics remarketing</a> function. Remarketing in Google Analytics makes it possible to encourage users who have previously visited the website to return using specially designed ads that target them as they visit other websites. A third-party cookie from DoubleClick is used for remarketing purposes. This cookie files is used to provide remarketing in such products as AdWords through the Google Display Network. Consider the following example scenario: after visiting Infotrip.org, the user decides to visit a travel blog that also participates in AdWords. Thanks to Google Analytics remarketing, the user will be shown ads encouraging them to use Infotrip.org.
                The user can prevent the Google system from using cookie files by visiting the appropriate page on Google to disable cookies.<br><br>
                The user can also use the following in order to change or disable Google Analytics:
                <ul>
                    <li><a href="https://adssettings.google.com/u/0/authenticated" target="_blank">Google Ads Preferences Manager;</a> </li>
                    <li><a href="https://tools.google.com/dlpage/gaoptout/" target="_blank"> Google Analytics Blocker.</a></li>
                </ul>
                You can find a description of Google’s advertising services and documentation regarding how they are used at <a href="https://www.google.com/services/#?modal_active=none" target="_blank"> http://www.google.com/services/</a><br><br>
                Google’s Privacy Policy is published here: <a href="https://policies.google.com/terms" target="_blank"> link</a>
                <h4>Other statistical tracking and social network integration tools</h4>
                <a href="https://www.facebook.com/policy.php" target="_blank"> Facebook login widget</a> <br><br>
                <a href="https://twitter.com/en/privacy" target="_blank"> Twitter login widget</a> <br><br>
                You can block all of the above tools, including Google tools, by installing third-party browser plug-ins (extensions).
                <h4>Personal information</h4>
                Your personal information, including e-mail address and name, cannot be disclosed to third parties, affiliates, and marketing contractors. This information may only be used by our company for marketing purposes with your consent. The following are exceptions to this rule:
                <ul>
                    <li>Lawful demands by government authorities,</li>
                    <li>Cases where the user provides explicit consent to the transfer of data to third parties in order to complete a booking</li>
                </ul>
                <h4>Changes to the Privacy Policy</h4>
                In the latter case, we at Infotrip.org shall not be liable for ensuring that third-party Internet services respect the confidentiality of user data. The User must independently consider and accept the terms and conditions governing confidentiality (the privacy policy) of any and all third-party websites that are linked to from Infotrip.org.<br><br>
                The Privacy Policy may change. All changes made to this document will be published on this page.<br><br>
                If you have any additional questions or concerns about the privacy policy, then you can contact the Infotrip.org administration by e-mail at: contact@infotrip.org

            </div>
        </div>
        <div class="gap"></div>
    </div>

<?php require_once $this->getTemplatePath() . 'includes/scripts.phtml'; ?>
<?php require_once $this->getTemplatePath() . 'includes/footer.phtml'; ?>


