<?php

/** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
$routeHelper = $viewHelpers['routeHelper'];

/** @var \Infotrip\Domain\Entity\Hotel[] $hotels */

//throw new Exception('test');
require_once $this->getTemplatePath() . 'includes/header.phtml';
?>

<div class="container">
    <div class="gap gap-small"></div>
    <h3 class="mb20">
        Hotels in
        <?php if (isset($areaSearch['city']) && $areaSearch['city']): ?>
        <?= strtoupper($areaSearch['city']); ?>
        <?php endif; ?>
    </h3>
    <div class="row row-wrap">
        <?php foreach ($hotels as $hotel): ?>
            <div class="col-md-3" style="height: 200px;">
                <div class="thumb">
                    <a class="hover-img"
                       target="_blank"
                       href="<?= $hotel->getBookingHotelUrl(); ?>">
                        <img src="<?= $hotel->getImages()[0]->getSrc(); ?>" alt="<?= $hotel->getBookingHotelUrl(); ?>"
                             style="height: 200px;"
                             title="Image hotel" />
                        <div class="hover-inner hover-inner-block hover-inner-bottom hover-inner-bg-black hover-hold">
                            <div class="text-small">
                                <h5><?= $hotel->getName(); ?></h5>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="gap gap-small"></div>
</div>

<?php require_once $this->getTemplatePath() . 'includes/hotel-search.phtml'; ?>


<?php require_once $this->getTemplatePath() . 'includes/scripts.phtml'; ?>
<?php require_once $this->getTemplatePath() . 'includes/footer.phtml'; ?>



