<?php

/** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
$routeHelper = $viewHelpers['routeHelper'];

require_once $this->getTemplatePath() . 'includes/header.phtml';
?>



<div class="global-wrap">

    <div class="container">
        <h1 class="page-title">Admin dashborad</h1>
    </div>


    <div class="container">
        <div class="row">
            <div class="col-md-12">



            </div>
        </div>
        <div class="gap"></div>
    </div>



    <?php require_once $this->getTemplatePath() . 'includes/scripts.phtml'; ?>

    <?php require_once $this->getTemplatePath() . 'includes/footer.phtml'; ?>


