<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-start.phtml';
?>

<div class="row">
    <div class="col-md-12">
        <div class="box-inn-sp">
            <div class="inn-title">
                <h4>All Hotel</h4>
                <p>Airtport Hotels The Right Way To Start A Short Break Holiday</p>
                <a class="dropdown-button drop-down-meta" href="#" data-activates="dr-users"><i class="material-icons">more_vert</i></a>
                <ul id="dr-users" class="dropdown-content">
                    <li><a href="#!">Add New</a>
                    </li>
                    <li><a href="#!">Edit</a>
                    </li>
                    <li><a href="#!">Update</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="#!"><i class="material-icons">delete</i>Delete</a>
                    </li>
                    <li><a href="#!"><i class="material-icons">subject</i>View All</a>
                    </li>
                </ul>

                <!-- Dropdown Structure -->

            </div>
            <div class="tab-inn">
                <div class="table-responsive table-desi">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>User</th>
                            <th>Hotel</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Country</th>
                            <th>View</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><span class="list-img"><img src="admin/images/listing/1.jpeg" alt=""></span>
                            </td>
                            <td><a href="#"><span class="list-enq-name">Domestic Help Services</span><span class="list-enq-city">Illunois, United States</span></a>
                            </td>
                            <td>+01 3214 6522</td>
                            <td>chadengle@dummy.com</td>
                            <td>Australia</td>
                            <td>
                                <a href="hotel-edit.html"><i class="fa fa-eye" aria-hidden="true"></i></a>
                            </td>
                            <td>
                                <a href="hotel-edit.html"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            </td>
                            <td>
                                <a href="#"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                            </td>
                        </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-end.phtml';
?>