<?php
/** @var $hotelOwnerUser \Infotrip\Domain\Entity\HotelOwnerUser */
/** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
/** @var $adminUiService \Infotrip\Utils\UI\Admin\Admin */
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-start.phtml';
?>

<div class="row">
    <div class="col-md-12">
        <div class="box-inn-sp">
            <div class="inn-title">
                <h4>All Hotels</h4>
                <a class="dropdown-button drop-down-meta" href="#" data-activates="dr-users"><i class="material-icons">more_vert</i></a>
                <ul id="dr-users" class="dropdown-content">
                    <li><a href="<?= $routeHelper->getHotelOwnerAdminAddNewHotelUrl(); ?>">Add New</a></li>
                </ul>

                <!-- Dropdown Structure -->

            </div>
            <div class="tab-inn">

                <?php if (isset($successMessage) && $successMessage): ?>
                    <div class="alert alert-success" role="alert">
                        <?= $successMessage; ?>
                    </div>
                <?php endif; ?>

                <?php if ($hotelOwnerUser->hasAssociatedHotels()): ?>
                <div class="table-responsive table-desi">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Hotel name</th>
                            <th>Address/zip</th>
                            <th>View</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i=1; foreach ($hotelOwnerUser->getAssociatedHotels() as $associatedHotel): ?>
                        <tr>
                            <td>
                                <?= $i; ?>
                            </td>
                            <td>
                                <span class="list-enq-name"><?= $associatedHotel->getName(); ?></span>
                                <span class="list-enq-city"><?= $associatedHotel->getCityHotel(); ?>, <?= $associatedHotel->getCountryName(); ?></span>
                            </td>
                            <td>
                                <?= $associatedHotel->getAddress(); ?>, <?= $associatedHotel->getZip(); ?>
                            </td>
                            <td>
                                <a href="<?= $routeHelper->getHotelUrl($associatedHotel->getName(), $associatedHotel->getId()); ?>" target="_blank"><i class="fa fa-eye" aria-hidden="true"></i></a>
                            </td>
                            <td>

                                <a href="<?= $routeHelper->getHotelOwnerAdminEditHotelUrl($associatedHotel->getId()); ?>"
                                target="_blank"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            </td>
                            <td>
                                <a href="<?= $routeHelper->getHotelOwnerAdminDeleteHotelUrl($associatedHotel->getId()); ?>" onclick="return confirm('Are you sure you want to delete the hotel. The hotel will not be visible anymore on infotirp.org')"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                        <?php $i++; endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <?php else: ?>
                <div style="color: red;">
                    <p>
                        You don't yet have any associated hotel.
                    </p>
                    <p>
                        Your account is verified. You will receive a notification when your account will be configured.
                    </p>
                </div>
                <?php endif; ?>

            </div>
        </div>
    </div>
</div>

<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-end.phtml';
?>