<?php
/** @var $hotelOwnerUser \Infotrip\Domain\Entity\HotelOwnerUser */
/** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
/** @var $adminUiService \Infotrip\Utils\UI\Admin\Admin */
/** @var $hotel \Infotrip\Domain\Entity\Hotel */
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-start.phtml';
?>

    <div class="row">
        <div class="col-md-12">
            <div class="box-inn-sp">
                <div class="sb2-2-add-blog sb2-2-1">
                    <h2>Edit Hotel</h2>
                    <p></p>

                    <ul class="nav nav-tabs tab-list">
                        <li class="active"><a data-toggle="tab" href="#home"><i class="fa fa-info" aria-hidden="true"></i> <span>Detail</span></a>
                        </li>
                        <li><a data-toggle="tab" href="#menu1"><i class="fa fa-picture-o" aria-hidden="true"></i> <span>Photo Gallery</span></a>
                        </li>
                        <li><a data-toggle="tab" href="#menu2"><i class="fa fa-phone" aria-hidden="true"></i> <span>Contact Info</span></a>
                        </li>
                        <li><a data-toggle="tab" href="#menu3"><i class="fa fa-facebook" aria-hidden="true"></i> <span>Social Media</span></a>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <div id="home" class="tab-pane fade in active">
                            <div class="box-inn-sp">
                                <div class="inn-title">
                                    <h4>Listing Information</h4>
                                </div>
                                <div class="bor">
                                    <form method="post"
                                    action="<?= $routeHelper->getHotelOwnerAdminEditHotelProcessUrl($hotel->getId()); ?>">
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input id="hotelName" name="hotelName"
                                                       required
                                                       type="text" class="validate" value="<?= $hotel->getName(); ?>">
                                                <label for="hotelName">Hotel name</label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <textarea required id="hotelDescription" name="hotelDescription"
                                                          class="materialize-textarea"><?= $hotel->getDescEn(); ?></textarea>
                                                <label for="hotelDescription">Hotel Description</label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input required id="hotelAddress" name="hotelAddress"
                                                       type="text" class="validate" value="<?= $hotel->getAddress(); ?>">
                                                <label for="hotelAddress">Hotel address</label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input required id="hotelZipCode" name="hotelZipCode"
                                                       type="text" class="validate" value="<?= $hotel->getZip(); ?>">
                                                <label for="hotelZipCode">Hotel zip code</label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input required id="hotelPriceMin" name="hotelPriceMin"
                                                       type="text" class="validate" value="<?= $hotel->getMinrate(); ?>">
                                                <label for="hotelPriceMin">Hotel zip code</label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input type="submit" class="waves-effect waves-light btn-large" value="Save">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div id="menu1" class="tab-pane fade">
                            <div class="inn-title">
                                <h4>Photo Gallery</h4>
                            </div>
                            <div class="bor">
                                <form action="#">
                                    <div class="file-field input-field">
                                        <div class="btn">
                                            <span>File</span>
                                            <input type="file" multiple>
                                        </div>
                                        <div class="file-path-wrapper">
                                            <input class="file-path validate" type="text" placeholder="Upload one or more files">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input type="submit" class="waves-effect waves-light btn-large" value="Upload">
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                        <div id="menu2" class="tab-pane fade">
                            <div class="inn-title">
                                <h4>Contact Info (Coming soong)</h4>
                            </div>
                            <?php /*
                            <div class="bor">
                                <form>
                                    <div class="row">
                                        <div class="input-field col s6">
                                            <input id="t5-n1" type="text" class="validate">
                                            <label for="t5-n1">Contact Name</label>
                                        </div>
                                        <div class="input-field col s6">
                                            <input id="t5-n2" type="text" class="validate">
                                            <label for="t5-n2">Alter Contact Name</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s6">
                                            <input id="t5-n3" type="number" class="validate">
                                            <label for="t5-n3">Phone</label>
                                        </div>
                                        <div class="input-field col s6">
                                            <input id="t5-n4" type="number" class="validate">
                                            <label for="t5-n4">Mobile</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input id="t5-n5" type="email" class="validate">
                                            <label for="t5-n5">Email</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <textarea id="t5-n6" class="materialize-textarea"></textarea>
                                            <label for="t5-n6">Listing Descriptions:</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input type="submit" class="waves-effect waves-light btn-large" value="Upload">
                                        </div>
                                    </div>
                                </form>
                            </div>
                            */ ?>
                        </div>
                        <div id="menu3" class="tab-pane fade">
                            <div class="inn-title">
                                <h4>Social Media (Coming soong)</h4>
                            </div>
                            <?php /*
                            <div class="bor">
                                <form>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input id="t4-soc1" type="text" value="http://facebook.com/" class="validate">
                                            <label for="t4-soc1">Facebook Url</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input id="t4-soc2" type="text" value="http://google.com/gplus" class="validate">
                                            <label for="t4-soc2">Google Plus Url</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input id="t4-soc3" type="text" value="http://twitter.com/" class="validate">
                                            <label for="t4-soc3">Twitter Url</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input id="t4-soc4" type="text" value="http://Linkedin.com/" class="validate">
                                            <label for="t4-soc4">Linkedin Url</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input id="t4-soc5" type="text" class="validate">
                                            <label for="t4-soc5">WhatsApp Number</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input id="t4-soc6" type="text" value="http://vk.com/" class="validate">
                                            <label for="t4-soc6">Vk Url</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input type="submit" class="waves-effect waves-light btn-large" value="Upload">
                                        </div>
                                    </div>
                                </form>
                            </div>
                            */ ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php
require_once $this->getTemplatePath() . 'hotelOwners/admin/layout/layout-end.phtml';
?>