<?php

/** @var $routeHelper \Infotrip\ViewHelpers\RouteHelper */
$routeHelper = $viewHelpers['routeHelper'];

/** @var \Infotrip\Domain\Entity\Country[] $contries */

/** @var \Infotrip\Domain\Entity\Country[][] $countries4Chunk */
$countries4Chunk = array_chunk($contries, 4);

require_once $this->getTemplatePath() . 'includes/header.phtml';
?>

<div class="container list-page">
    <div class="gap gap-small"></div>


    <?php
    if(count($countries4Chunk)):
    $firstCountry = $countries4Chunk[0][0];
    ?>
    <ul class="breadcrumb">
        <li><a href="<?= $routeHelper->getHomepageUrl(); ?>">Home</a>
        </li>
        <li class="active"><?php echo $firstCountry->getContinent()->getName(); ?></li>
    </ul>
    <?php endif; ?>

    <?php if($resourceContent instanceof \Infotrip\Domain\Entity\ResourceContent): ?>
        <div class="row row-wrap">
            <div class="col-md-12">

                <h2>
                    <?= strtoupper($resourceContent->getResourceName()); ?>
                </h2>
                <div>
                    <?= $resourceContent->getContent(); ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <h3 class="mb20">Choose a country</h3>
    <?php foreach ($countries4Chunk as $row): ?>
        <div class="row row-wrap">
        <?php foreach ($row as $country): ?>
            <div class="col-md-3">
                <div class="thumb">
                    <a class="list-link"
                            href="<?= $routeHelper->getListCitiesUrl($country->getId(), $country->getName()); ?>">
                        <h5><?= $country->getName(); ?></h5>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
    <div class="gap gap-small"></div>
</div>


<?php require_once $this->getTemplatePath() . 'includes/scripts.phtml'; ?>
<?php require_once $this->getTemplatePath() . 'includes/footer.phtml'; ?>



