<?php

namespace Infotrip\ViewHelpers;


class RandomUrlsHelper
{
    /**
     * @var RouteHelper
     */
    private $routeHelper;

    public static $COUNTRY_WITH_HOTELS = array(
        "AD",
        "AE",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CU",
        "CV",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TC",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "YT",
        "ZA",
        "ZM",
        "ZW",
    );

    public static $CITIES_WITH_HOTELS = array(
        "rome",
        "paris",
        "rio",
        "saint",
        "kissimmee",
        "london",
        "split",
        "lisbon",
        "davenport",
        "florence",
        "budapest",
        "moscow",
        "barcelona",
        "istanbul",
        "prague",
        "milan",
        "trogir",
        "zadar",
        "dubrovnik",
        "bangkok",
        "pula",
        "krakow",
        "venice",
        "madrid",
        "tbilisi",
        "beijing",
        "amsterdam",
        "myrtle",
        "gdansk",
        "shanghai",
        "marrakech",
        "belgrade",
        "orlando",
        "seoul",
        "cannes",
        "guangzhou",
        "naples",
        "batumi",
        "vienna",
        "warsaw",
        "budva",
        "nice",
        "buenos",
        "porto",
        "santiago",
        "chiang",
        "makarska",
        "rovinj",
        "ubud",
        "zagreb",
        "berlin",
        "new",
        "palermo",
        "porec",
        "adler",
        "seminyak",
        "ho",
        "cape",
        "sopot",
        "steamboat",
        "playa",
        "vodice",
        "dubai",
        "zakopane",
        "los",
        "mammoth",
        "lima",
        "blavand",
        "new",
        "bucharest",
        "novalja",
        "rimini",
        "xi",
        "tokyo",
        "chengdu",
        "verona",
        "albufeira",
        "sunny",
        "lviv",
        "minsk",
        "hilton",
        "calpe",
        "florianopolis",
        "sarajevo",
        "sao",
        "gramado",
        "kuala",
        "crikvenica",
        "siemreab",
        "melbourne",
        "kiev",
        "edinburgh",
        "ban",
        "destin",
        "siracusa",
        "qingdao",
        "hangzhou",
        "hanoi",
        "bogota",
        "kyoto",
        "kastela",
        "ebeltoft",
        "odesa",
        "yerevan",
        "athens",
        "valencia",
        "brussels",
        "fort",
        "bangalore",
        "rab",
        "cusco",
        "yekaterinburg",
        "jakarta",
        "sydney",
        "shenzhen",
        "hong",
        "sochi",
        "cartagena",
        "medulin",
        "blackpool",
        "marbella",
        "fortaleza",
        "catania",
        "chamonix",
        "torino",
        "riga",
        "malaga",
        "tel",
        "kandy",
        "podstrana",
        "south",
        "dayan",
        "vilnius",
        "alghero",
        "sanya",
        "sevilla",
        "malinska",
        "umag",
        "hua",
        "bologna",
        "palanga",
        "mexico",
        "san",
        "anapa",
        "boto",
        "matera",
        "lecce",
        "kotor",
        "xiamen",
        "benidorm",
        "jaipur",
        "gelendzhik",
        "granada",
        "big",
        "manila",
        "phnom",
        "buzios",
        "sibenik",
        "protaras",
        "trapani",
        "danang",
        "tallinn",
        "mamaia",
        "romo",
        "miami",
        "kazan",
        "puerto",
        "castellammare",
        "lucca",
        "torrevieja",
        "salou",
        "lagos",
        "rogoznica",
        "lido",
        "san",
        "panama",
        "hvar",
        "fazana",
        "gold",
        "orebic",
        "cologne",
        "zermatt",
        "pollenassa",
        "vina",
        "houston",
        "gdynia",
        "hua",
        "san",
        "singapore",
        "hoi",
        "bombay",
        "lyon",
        "munich",
        "sofia",
        "chongqing",
        "novi",
        "siofok",
        "gallipoli",
        "javea",
        "salvador",
        "canggu",
        "suzhou",
        "sudak",
    );


    /**
     * RandomUrlsHelper constructor.
     * @param RouteHelper $routeHelper
     */
    public function __construct(
        RouteHelper $routeHelper
    )
    {
        $this->routeHelper = $routeHelper;
    }

    /**
     * Get random country urls
     *
     * @param int $no
     * @return array
     */
    public function getRandomCountryUrls(
        $no = 7
    )
    {
        $countries = self::$COUNTRY_WITH_HOTELS;
        shuffle($countries);

        $slice = array_slice($countries, 0, $no);

        $urls = array();

        foreach ($slice as $countryCode) {

            $url = $this->routeHelper->getHotelsInUrl('', $countryCode);
            $countryName = \Infotrip\Domain\Entity\Country::$COUNTRY_CODE_LIST[$countryCode];

            $urls[] = array(
                'label' => $countryName,
                'url' => $url,
            );
        }

        return $urls;
    }

    /**
     * Get random city urls
     *
     * @param int $no
     * @return array
     */
    public function getRandomCityUrls(
        $no = 7
    )
    {
        $cities = self::$CITIES_WITH_HOTELS;
        shuffle($cities);

        $slice = array_slice($cities, 0, $no);

        $urls = array();

        foreach ($slice as $cityUnique) {
            $url = $this->routeHelper->getHotelsInUrl($cityUnique);

            $urls[] = array(
                'label' => ucwords($cityUnique),
                'url' => $url,
            );
        }

        return $urls;
    }
}